### PR TITLE
Fix for white stripe over horizon

### PR DESCRIPTION
**Pull request by MaximeDup**
comparison

### CODE REVIEW

**Comment by MaximeDup** [comment]
From Unreal Engine:
comparison2

**Comment by ebruneton** [comment]
Thanks for this! It seems you ported and adapted the hack from the initial implementation? In your change 'a' is no longer used and it seems you just clamp 'mu' to some value just above the horizon?

I tried a simplified version with

```
--- a/atmosphere/functions.glsl
+++ b/atmosphere/functions.glsl
@@ -1806,6 +1806,14 @@ RadianceSpectrum GetSkyRadianceToPoint(
   Length d = length(point - camera);
   bool ray_r_mu_intersects_ground = RayIntersectsGround(atmosphere, r, mu);
 
+  // Hack to avoid rendering artifacts near the horizon, due to finite
+  // atmosphere texture resolution and finite floating point precision.
+  if (!ray_r_mu_intersects_ground) {
+    Number mu_horiz = -SafeSqrt(
+        1.0 - (atmosphere.bottom_radius / r) * (atmosphere.bottom_radius / r));
+    mu = max(mu, mu_horiz + 0.004);
+  }
+
   transmittance = GetTransmittance(atmosphere, transmittance_texture,
       r, mu, d, ray_r_mu_intersects_ground);
```

and it seems to give more or less the same results. Can you confirm?

**Comment by MaximeDup** [comment]
Your fix worked like a charm!
Appears my issue was mostly coming from my textures. I've a hard time reproducing it again now that it's fixed. Not using the shadow length seems to make it a bit harder to get clean result for shadowed part, might have still have texture issues:
https://www.youtube.com/watch?v=VH2ZYGz9IMo

**Comment by MaximeDup** [comment]
Result were very similar, and your solution much more elegant!
I ended up not using this fix after improving my texture generation during precompute phase.
Current iteration:
https://www.youtube.com/watch?v=wPGMbprrtDA

**Comment by MaximeDup** [comment]
Screen from current UE4 version. I've read several other people implemented your latest atmosphere version in UE4, one of which gonna be sold on the marketplace. Might get better results than mine, but i'm really satisfied with mine so far!
atmo

**Comment by ebruneton** [comment]
Impressive work! Since you don't need the patch in the end, I will not commit it.

**Comment by Ralith** [comment]
>  I ended up not using this fix after improving my texture generation during precompute phase.

Can you elaborate on what changes were necessary? Are they something that could be upstreamed here?

**Comment by Ralith** [comment]
I'd still love to have some clarity here. What's the proper solution to the severe artifacts that can occur?

**Pull request closed without merging**
